name: qiime2-2019.7
channels:
  - qiime2/label/r2019.7
  - bioconda
  - conda-forge
  - https://conda.anaconda.org/qiime2/label/r2017.6
  - https://conda.anaconda.org/qiime2
  - https://conda.anaconda.org/biocore
  - https://conda.anaconda.org/bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - appnope=0.1.0=py36_1000
  - arb-bio-tools=6.0.6=h82bc0eb_8
  - asn1crypto=0.24.0=py36_1003
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bibtexparser=1.1.0=py_0
  - bioconductor-biobase=2.42.0=r351h1de35cc_1
  - bioconductor-biocgenerics=0.28.0=r351_1
  - bioconductor-biocparallel=1.16.6=r351h71abe9c_0
  - bioconductor-biostrings=2.50.2=r351h1de35cc_0
  - bioconductor-dada2=1.10.0=r351h0a44026_0
  - bioconductor-delayedarray=0.8.0=r351h1de35cc_0
  - bioconductor-genomeinfodb=1.18.1=r351_0
  - bioconductor-genomeinfodbdata=1.2.1=r351_0
  - bioconductor-genomicalignments=1.18.1=r351h1de35cc_0
  - bioconductor-genomicranges=1.34.0=r351h1de35cc_0
  - bioconductor-iranges=2.16.0=r351h1de35cc_0
  - bioconductor-rsamtools=1.34.0=r351h0a44026_0
  - bioconductor-s4vectors=0.20.1=r351h470a237_0
  - bioconductor-shortread=1.40.0=r351h0a44026_0
  - bioconductor-summarizedexperiment=1.12.0=r351_0
  - bioconductor-xvector=0.22.0=r351h1de35cc_0
  - bioconductor-zlibbioc=1.28.0=r351h1de35cc_0
  - biom-format=2.1.7=py36h917ab60_1002
  - blas=2.11=openblas
  - blast=2.9.0=pl526hb2f8ae4_4
  - bleach=3.1.0=py_0
  - bokeh=1.3.1=py36_0
  - boost=1.68.0=py36h9888f84_1001
  - boost-cpp=1.68.0=h6f8c590_1000
  - bwidget=1.9.11=0
  - bz2file=0.98=py_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cachecontrol=0.12.5=py_0
  - cairo=1.16.0=h0ab9d94_1001
  - cctools=895=h7512d6f_0
  - certifi=2019.11.28=py36h9f0ad1d_1
  - cffi=1.12.3=py36hccf1714_0
  - chardet=3.0.4=py36_1003
  - clang=4.0.1=h662ec87_0
  - clang_osx-64=4.0.1=h1ce6c1d_17
  - clangxx=4.0.1=hc9b4283_0
  - clangxx_osx-64=4.0.1=h22b1bf0_17
  - click=7.0=py_0
  - compiler-rt=4.0.1=h5487866_0
  - cryptography=2.7=py36h212c5bf_0
  - curl=7.65.3=h22ea746_0
  - cutadapt=2.4=py36h1de35cc_0
  - cython=0.29.13=py36h6de7cb9_0
  - dash=1.9.1=py_0
  - dash-core-components=1.8.1=py_0
  - dash-html-components=1.0.2=py_0
  - dash-renderer=1.2.4=py_0
  - dash-table=4.6.1=py_0
  - deblur=1.1.0=py36_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - dnaio=0.3=py36h1de35cc_1
  - emperor=1.0.0b19=py36_0
  - entrez-direct=11.0=pl526_0
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=h6de7cb9_1003
  - fastcluster=1.1.25=py36h1702cab_1000
  - fasttree=2.1.10=0
  - flask=1.1.1=py_1
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.10.0=h24853df_1
  - future=0.17.1=py36_1000
  - gettext=0.19.8.1=h46ab8bc_1002
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - glib=2.58.3=h9d45998_1002
  - gmp=6.1.2=h0a44026_1000
  - gneiss=0.4.5=py_0
  - gnutls=3.6.5=h53004b3_1002
  - graphite2=1.3.13=h2098e52_1000
  - gsl=2.5=ha2d443c_1
  - h5py=2.9.0=nompi_py36h3d62f72_1103
  - harfbuzz=2.4.0=h92b87b8_1
  - hdf5=1.10.4=nompi_h0cbb7df_1106
  - hdmedians=0.13=py36heacc8b8_1001
  - icu=58.2=h0a44026_1000
  - idna=2.8=py36_1000
  - ijson=2.3=py_1
  - importlib_metadata=0.18=py36_0
  - ipykernel=5.1.1=py36h5ca1d4c_0
  - ipython=7.7.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - iqtree=1.6.11.1=h2dec4b4_0
  - itsdangerous=1.1.0=py_0
  - jedi=0.14.1=py36_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py36h770b8ee_0
  - krb5=1.16.3=hcfa6398_1001
  - ld64=274.2=h7c2db76_0
  - libarbdb=6.0.6=h82bc0eb_8
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgcc=4.8.5=hdbeacc1_10
  - libgfortran=3.0.1=0
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=hd44dcd8_6
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.0.10=hd08fb8f_1003
  - libxml2=2.9.9=hd80cff7_2
  - llvm=4.0.1=hc748206_0
  - llvm-lto-tapi=4.0.1=h6701bc3_0
  - llvm-openmp=8.0.0=h770b8ee_1
  - lockfile=0.12.2=py_1
  - lz4-c=1.8.3=h6de7cb9_1001
  - mafft=7.310=h0a44026_2
  - make=4.2.1=h1de35cc_2004
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - mistune=0.8.4=py36h1de35cc_1000
  - more-itertools=7.2.0=py_0
  - msgpack-python=0.6.1=py36h04f5b5a_0
  - natsort=6.0.0=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - nettle=3.4.1=h3efe00b_1002
  - networkx=2.3=py_0
  - nose=1.3.7=py36_1002
  - notebook=6.0.0=py36_0
  - numpy=1.17.0=py36h6b0580a_0
  - olefile=0.46=py_0
  - openjdk=11.0.1=h01d97ff_1017
  - openmp=8.0.0=1
  - openssl=1.1.1e=h0b31af3_0
  - packaging=19.0=py_0
  - pandas=0.24.2=py36h86efe34_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=h0da9b22_1005
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=h0a44026_1003
  - perl=5.26.2=haec8ef5_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.086=pl526h0a44026_0
  - perl-compress-raw-zlib=2.086=pl526h04f5b5a_1
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h04f5b5a_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.086=pl526h0a44026_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h04f5b5a_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526hb1dc21d_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h1de35cc_1
  - perl-scalar-list-utils=1.50=pl526h1de35cc_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h1de35cc_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526h4c9d1cc_1002
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pigz=2.3.4=0
  - pillow=6.0.0=py36h7095ceb_0
  - pip=19.2.1=py36_0
  - pixman=0.38.0=h01d97ff_1003
  - plotly=4.5.4=pyh8c360ce_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py36h01d97ff_0
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pycairo=1.18.2=py36h83b1bec_0
  - pycparser=2.19=py36_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.0=py_0
  - pyrsistent=0.15.4=py36h01d97ff_0
  - pysocks=1.7.0=py36_0
  - pytest=5.0.1=py36_1
  - python=3.6.7=h94afb7f_1005
  - python-dateutil=2.8.0=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py36h01d97ff_0
  - pyzmq=18.0.2=py36hee98d25_2
  - q2-alignment=2019.7.0=py36_0
  - q2-composition=2019.7.0=py36_0
  - q2-cutadapt=2019.7.0=py36_0
  - q2-dada2=2019.7.0=py36_0
  - q2-deblur=2019.7.0=py36_0
  - q2-demux=2019.7.0=py36_0
  - q2-diversity=2019.7.0=py36_0
  - q2-emperor=2019.7.0=py36_0
  - q2-feature-classifier=2019.7.0=py36_0
  - q2-feature-table=2019.7.0=py36_0
  - q2-fragment-insertion=2019.7.0=py36_0
  - q2-gneiss=2019.7.0=py36_0
  - q2-longitudinal=2019.7.0=py36_0
  - q2-metadata=2019.7.0=py36_0
  - q2-phylogeny=2019.7.0=py36_0
  - q2-quality-control=2019.7.0=py36_0
  - q2-quality-filter=2019.7.0=py36_0
  - q2-sample-classifier=2019.7.1=py36_0
  - q2-taxa=2019.7.0=py36_0
  - q2-types=2019.7.0=py36_0
  - q2-vsearch=2019.7.0=py36_0
  - q2cli=2019.7.0=py36_0
  - q2templates=2019.7.0=py36_0
  - qiime2=2019.7.0=py36_0
  - r-assertthat=0.2.1=r35h6115d3f_1
  - r-backports=1.1.4=r35h159158b_1
  - r-base=3.5.1=h49b657e_1008
  - r-bh=1.69.0_1=r35h6115d3f_1
  - r-bitops=1.0_6=r35h159158b_1003
  - r-cli=1.1.0=r35h6115d3f_2
  - r-cluster=2.1.0=r35haf69682_2
  - r-colorspace=1.4_1=r35h159158b_1
  - r-crayon=1.3.4=r35h6115d3f_1002
  - r-data.table=1.12.2=r35h159158b_1
  - r-digest=0.6.20=r35hf99fc2c_1
  - r-ellipsis=0.2.0.1=r35h159158b_1
  - r-fansi=0.4.0=r35h159158b_1001
  - r-formatr=1.7=r35h6115d3f_1
  - r-futile.logger=1.4.3=r35h6115d3f_1002
  - r-futile.options=1.0.1=r35h6115d3f_1001
  - r-ggplot2=3.2.0=r35h6115d3f_1
  - r-glue=1.3.1=r35h159158b_1
  - r-gtable=0.3.0=r35h6115d3f_2
  - r-hwriter=1.3.2=r35h6115d3f_1002
  - r-labeling=0.3=r35h6115d3f_1002
  - r-lambda.r=1.2.3=r35h6115d3f_1001
  - r-lattice=0.20_38=r35h159158b_1002
  - r-latticeextra=0.6_28=r35h6115d3f_1002
  - r-lazyeval=0.2.2=r35h159158b_1
  - r-magrittr=1.5=r35h6115d3f_1002
  - r-mass=7.3_51.4=r35h159158b_1
  - r-matrix=1.2_17=r35h159158b_1
  - r-matrixstats=0.54.0=r35h159158b_1001
  - r-mgcv=1.8_28=r35h159158b_1
  - r-munsell=0.5.0=r35h6115d3f_1002
  - r-nlme=3.1_140=r35haf69682_1
  - r-permute=0.9_5=r35_1
  - r-pillar=1.4.2=r35h6115d3f_2
  - r-pkgconfig=2.0.2=r35h6115d3f_1003
  - r-plyr=1.8.4=r35hf99fc2c_1003
  - r-r6=2.4.0=r35h6115d3f_2
  - r-rcolorbrewer=1.1_2=r35h6115d3f_1002
  - r-rcpp=1.0.2=r35hf99fc2c_0
  - r-rcppparallel=4.4.3=r35hf99fc2c_2
  - r-rcurl=1.95_4.12=r35h159158b_1
  - r-reshape2=1.4.3=r35hf99fc2c_1004
  - r-rlang=0.4.0=r35h159158b_1
  - r-scales=1.0.0=r35hf99fc2c_1002
  - r-snow=0.4_3=r35h6115d3f_1001
  - r-stringi=1.4.3=r35hf99fc2c_2
  - r-stringr=1.4.0=r35h6115d3f_1
  - r-tibble=2.1.3=r35h159158b_1
  - r-utf8=1.1.4=r35h159158b_1001
  - r-vctrs=0.2.0=r35h159158b_1
  - r-vegan=2.5_5=r35haf69682_2
  - r-viridislite=0.3.0=r35h6115d3f_1002
  - r-withr=2.1.2=r35h6115d3f_1001
  - r-zeallot=0.1.0=r35h6115d3f_1001
  - raxml=8.2.12=h1de35cc_1
  - rdkit=2019.03.2=py36haff9cca_0
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py36_1
  - scikit-bio=0.5.5=py36h917ab60_1000
  - scipy=1.3.0=py36hab3da7d_1
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sina=1.6.0=hf49611d_0
  - six=1.12.0=py36_1000
  - sortmerna=2.0=h5c9b4e4_4
  - sqlite=3.29.0=hb7d70f7_1
  - statsmodels=0.10.1=py36heacc8b8_0
  - tbb=2019.7=h770b8ee_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h2573ce8_1003
  - tktable=2.10=hfa822fa_2
  - tornado=6.0.3=py36h01d97ff_0
  - traitlets=4.3.2=py36_1000
  - tzlocal=2.0.0=py_0
  - unifrac=0.10.0=py36h04f5b5a_1
  - urllib3=1.25.3=py36_0
  - vsearch=2.7.0=1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.0=py_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xopen=0.7.3=py_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h01d97ff_1006
  - zstd=1.4.0=ha9f0a20_0
  - pip:
    - autoflake==1.3.1
    - beautifulsoup4==4.8.2
    - calour==2019.5.1
    - cycler==0.10.0
    - dash-bootstrap-components==0.9.2
    - dbbact-calour==0.1
    - docrep==0.2.7
    - empress==0.1.dev0
    - flake8==3.7.9
    - flask-compress==1.4.0
    - gnps-calour==0.1
    - imbalanced-learn==0.6.2
    - iow==0.1.2
    - itolapi==4.0.0
    - mccabe==0.6.1
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pyside2==5.13.2
    - q2-qemistree==2020.1.3
    - retrying==1.3.3
    - scikit-learn==0.22.2.post1
    - shiboken2==5.13.2
    - soupsieve==2.0
prefix: /Users/priya/miniconda3/envs/qiime2-2019.7

